name: my_weather
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  easy_localization: ^2.3.3
  shadow: ^0.1.5
  location: ^3.0.0
  geocoding: ^1.0.5
  translator: ^0.1.5
  http: ^0.12.2
  weather: ^1.2.4
  flutter_bloc: ^5.0.0
  shared_preferences: ^0.5.12+4
  intl: ^0.16.1
  flutter_bounce: ^1.0.8
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1
  cloud_firestore: ^0.14.4
  google_sign_in: ^4.5.3
  cupertino_icons: ^1.0.0
  equatable: ^0.6.1
  connectivity: ^0.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/images/

  fonts:
    - family: Segoe
      fonts:
        - asset: assets/fonts/segoe.ttf